version: '3.9'
services:
  redis:
    image: "redis/redis-stack"
    restart: always
    environment:
      REDIS_ARGS: "--user test_user on >test_password allkeys allchannels allcommands --user default off"
    ports:
      - "6379:6379"
      - "8001:8001"
    expose:
      - "6379"
      - "8001"

  ferrum:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SCHEMA: http
        HOST: ferrum
        PORT: 8182

        REDIS_HOST: redis #name service in docker-compose
        REDIS_PORT: 6379
        REDIS_USER: test_user
        REDIS_PASSWORD: test_password

        NAMESPACE: ferrum_1
        DB_NUMBER: 0
    restart: always
    depends_on:
      - redis
    ports:
      - "8182:8182"
    expose:
      - "8182"
